apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: paymybuddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args: ["--datadir=/data"]
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: db_paymybuddy
          volumeMounts:
            - name: mysql-storage
              mountPath: /data
      volumes:
        - name: mysql-storage
          hostPath:
            path: /data/mysql
            type: DirectoryOrCreate
        - name: db-init-scripts
          configMap:
            name: db-init-scripts-configmap

