apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-webapp
  namespace: paymybuddy
spec:
  type: NodePort
  selector:
    app: paymybuddy-app  # ← correspond aux labels du Deployment
  ports:
    - port: 80            # Port exposé sur le cluster
      targetPort: 8081    # Port sur lequel le conteneur écoute
      nodePort: 30081     # Port sur le nœud (accessible en http://<NODE_IP>:30081)
